# Generated by Django 5.0.6 on 2025-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajoutstock',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='venteproduct',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
