# Generated by Django 5.0.6 on 2026-06-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_venteproduct_prix_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=50)),
                ('avance', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('trosa', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.customer'),
        ),
        migrations.AddField(
            model_name='filattenteproduct',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.customer'),
        ),
    ]
