# Generated by Django 5.0.6 on 2026-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_customer_facture_customer_filattenteproduct_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='filattenteproduct',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='ajoutstock',
            name='qte_apres',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ajoutstock',
            name='qte_avant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='num',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='reglement',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglement',
            name='type_r',
            field=models.CharField(blank=True, default='paiement', max_length=50),
        ),
        migrations.AddField(
            model_name='venteproduct',
            name='qte_apres',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='venteproduct',
            name='qte_avant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
