# Generated by Django 5.0.6 on 2026-06-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_customer_facture_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='stock.customer'),
        ),
        migrations.AlterField(
            model_name='filattenteproduct',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='stock.customer'),
        ),
    ]
