# Generated by Django 5.0.6 on 2026-06-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_facture_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='num',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
