# Generated by Django 5.0.6 on 2026-06-07 04:51
from django.db import migrations, models

def init_counter(apps, schema_editor):
    from django.utils import timezone
    InvoiceCounter = apps.get_model('stock', 'InvoiceCounter')
    InvoiceCounter.objects.get_or_create(
        year=timezone.now().year,
        defaults={"current": 0}
    )

class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0007_alter_facture_num'),
    ]
    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('current', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de facture',
            },
        ),
        migrations.RunPython(init_counter, migrations.RunPython.noop),  # après CreateModel
    ]