# Generated by Django 5.0.6 on 2026-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_invoicecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
