name: Deploy client67_c to VPS_Contabo

on:
  push:
    branches:
      - master  # ou develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    # 3️⃣ Créer le .env sur le VPS pour Project1
    - name: Create .env for client67
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
        mkdir -p ~/pharma_app/client67 &&
        echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' > ~/pharma_app/client67/.env &&
        echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> ~/pharma_app/client67/.env &&
        echo 'DB_USER=${{ secrets.DB_USER }}' >> ~/pharma_app/client67/.env &&
        echo 'DB_NAME=${{ secrets.DB_NAME }}' >> ~/pharma_app/client67/.env &&
        echo 'DEBUD=${{ secrets.DEBUG }}' >> ~/pharma_app/client67/.env
        echo 'DB_HOST=db' >> ~/pharma_app/client67/.env &&
        echo 'ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}' >> ~/pharma_app/client67/.env &&
        echo 'DB_PORT=3306' >> ~/pharma_app/client67/.env
        "

    # 4️⃣ Copier uniquement Project1 sur le VPS
    - name: Copy client67 to VPS
      run: |
        rsync -avz --exclude='.env' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/pharma_app/client67/

    # 5️⃣ Build et redémarre uniquement le conteneur Project1
    - name: Deploy client67 with Docker Compose
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
        cd ~/pharma_app/deployment &&
        docker compose build client67 &&
        docker compose up -d client67
        "
